version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./Rase-lara:/work


  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./Rase-lara:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: